version: '3.8'
services:
  app:
    build: .
    container_name: preview-1754512974038
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - preview-network

networks:
  preview-network:
    driver: bridge