version: '3.8'
services:
  app:
    build: .
    container_name: preview-1754513376642
    ports:
      - "4005:4005"
    environment:
      - PORT=4005
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - preview-network

networks:
  preview-network:
    driver: bridge