version: '3.8'
services:
  app:
    build: .
    container_name: preview-1754420242725
    ports:
      - "4003:4003"
    environment:
      - PORT=4003
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - preview-network

networks:
  preview-network:
    driver: bridge