version: '3.8'
services:
  app:
    build: .
    container_name: preview-1754419825999
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - preview-network

networks:
  preview-network:
    driver: bridge